---
name: 🧩 General Issue
about: 다양한 일반 이슈에 대한 템플릿
title: "[Issue]: "
labels: ["needs-triage"]
assignees: []
---

## 🚧 Issue Description
<!-- 어떤 이슈인가요? 무엇이 안되거나 필요한가요? -->
- 발생 배경 / 필요 이유를 적어주세요.

---

## 📌 Issue Detail
<!-- 이슈에 대한 구체적인 내용 -->
- 관련 파일 / 컴포넌트 / 함수
- 예상 동작 vs 실제 동작
- 스크린샷, 로그 등 (선택)

---

## ✔️ Resolution
<!-- 이슈가 해결된 방법, 주요 변경 사항 정리 -->
- 어떤 방식으로 해결했는지 기록해주세요
- 해결에 기여한 커밋/PR 링크 추가 가능

---

## 🛠️ 삽질로그
<!-- 디버깅 중 겪은 문제, 참고한 자료, 깨달은 점 등 자유롭게 작성 -->
- ex) "ESLint 충돌은 Prettier 설정 문제였다"
- ex) 참고 블로그: https://...

---

## 🔗 Related
<!-- 관련 이슈, 커밋, PR 등 -->
- Issue: #123
- PR: #456
