import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const styles = StyleSheet.create({
  bg: {
    flex: 1,
    backgroundColor: '#0a1633',
  },
  scrollContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 24,
    paddingHorizontal: 16,
    paddingLeft: 80,
    gap: 16,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 18,
    marginTop: 8,
    width: 280,
  },
  summaryCard: {
    backgroundColor: 'rgba(20,30,60,0.92)',
    borderRadius: 16,
    padding: 20,
    width: 280,
    height: 275,
  },
  summaryTitle: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    marginBottom: 16,
    marginTop: -5,
  },
  summaryList: {
    gap: 12,
  },
  summaryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 8,
  },
  summaryLabel: {
    color: '#b3b3ff',
    fontSize: 13,
    marginBottom: 6,
    fontWeight: 'bold',
  },
  summaryValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  section: {
    backgroundColor: 'rgba(20,30,60,0.92)',
    borderRadius: 16,
    padding: 16,
    width: 280,
    height: 275,
    justifyContent: 'center',
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    marginBottom: 14,
  },
  sectionContent: {
    flex: 1,
    justifyContent: 'center',
  },
  weekRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  weekDay: {
    color: '#b3b3ff',
    fontSize: 13,
    width: 70,
    fontWeight: 'bold',
  },
  weekDayLabel: {
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
    width: 22,
    marginRight: 6,
    textAlign: 'center',
  },
  weekBarBg: {
    flex: 1,
    height: 10,
    backgroundColor: '#1a2340',
    borderRadius: 6,
    marginHorizontal: 8,
    overflow: 'hidden',
  },
  weekBar: {
    height: 10,
    backgroundColor: '#3b82f6',
    borderRadius: 6,
  },
  weekMinutes: {
    color: '#fff',
    fontSize: 13,
    width: 36,
    textAlign: 'right',
  },
  goalBox: {
    backgroundColor: 'rgba(20,30,60,0.92)',
    borderRadius: 16,
    padding: 16,
    width: 280,
    height: 275,
    justifyContent: 'center',
  },
  goalTitle: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  goalContent: {
    flex: 1,
    justifyContent: 'center',
  },
  goalItem: {
    marginBottom: 10,
  },
  goalLabel: {
    color: '#b3b3ff',
    fontSize: 13,
    marginBottom: 2,
    fontWeight: 'bold',
  },
  goalBarBg: {
    width: '100%',
    height: 10,
    backgroundColor: '#1a2340',
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 2,
  },
  goalBar: {
    height: 10,
    backgroundColor: '#a18fff',
    borderRadius: 6,
  },
  goalValue: {
    color: '#fff',
    fontSize: 13,
    textAlign: 'right',
    marginBottom: 2,
  },
  keywordBox: {
    backgroundColor: 'rgba(20,30,60,0.92)',
    borderRadius: 16,
    padding: 16,
    width: 280,
    height: 275,
    justifyContent: 'center',
  },
  keywordTitle: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  keywordContent: {
    flex: 1,
    justifyContent: 'center',
  },
  keywordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  keywordTag: {
    backgroundColor: '#23284a',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 2,
    marginRight: 8,
  },
  keywordTagText: {
    color: '#b3b3ff',
    fontSize: 13,
    fontWeight: 'bold',
  },
  keywordBarBg: {
    flex: 1,
    height: 8,
    backgroundColor: '#1a2340',
    borderRadius: 6,
    marginRight: 8,
    overflow: 'hidden',
  },
  keywordBar: {
    height: 8,
    backgroundColor: '#3b82f6',
    borderRadius: 6,
  },
  keywordCount: {
    color: '#fff',
    fontSize: 13,
    width: 32,
    textAlign: 'right',
  },
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    backgroundColor: '#101a36',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 8,
    justifyContent: 'space-around',
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.13,
    shadowRadius: 6,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 2,
  },
  tabItemActive: {
    borderTopWidth: 3,
    borderTopColor: '#a18fff',
  },
  tabIcon: {
    width: 28,
    height: 28,
    marginBottom: 2,
    resizeMode: 'contain',
  },
  tabLabel: {
    color: '#b3b3ff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  tabLabelActive: {
    color: '#a18fff',
  },
});

export default styles;
