import { StyleSheet } from 'react-native';

export const MyPageStyles = StyleSheet.create({
  bg: {
    flex: 1,
    backgroundColor: '#F5F7FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowLayout: {
    flexDirection: 'row',
    width: '100%',
    maxWidth: 1200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
    paddingVertical: 40,
  },
  leftSection: {
    alignItems: 'center',
    marginRight: 56,
    minWidth: 200,
    flex: 1,
  },
  rightSection: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'stretch',
    width: '100%',
  },
  menuGrid: {
    flexDirection: 'column',
    gap: 32,
    justifyContent: 'center',
    alignItems: 'stretch',
    width: '100%',
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 18,
  },
  nickname: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#222',
  },
  nicknameInput: {
    fontSize: 22,
    fontWeight: 'bold',
    borderBottomWidth: 1,
    borderColor: '#aaa',
    paddingVertical: 2,
    minWidth: 80,
    marginBottom: 4,
    color: '#222',
    backgroundColor: '#f9f9f9',
  },
  name: {
    fontSize: 15,
    color: '#888',
    marginBottom: 2,
  },
  menuButton: {
    backgroundColor: '#f8f8f8',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 220,
    minHeight: 70,
    width: '100%',
    marginBottom: 0,
    paddingVertical: 24,
    paddingHorizontal: 10,
  },
  squareButton: {
    minWidth: 220,
    minHeight: 70,
    width: '100%',
  },
  menuButtonText: {
    fontSize: 18,
    color: '#333',
    textAlign: 'center',
  },
  settingsButtonCard: {
    display: 'none',
  },
  settingsButtonOutside: {
    position: 'absolute',
    top: 32,
    right: 48,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 6,
    zIndex: 20,
  },
  settingsIcon: {
    width: 26,
    height: 26,
  },
  backButton: {
    position: 'absolute',
    top: 32,
    left: 32,
    zIndex: 30,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 6,
  },
  backIcon: {
    fontSize: 26,
    color: '#222',
  },
});
