import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  bg: { flex: 1, width: '100%', height: '100%' },
  scrollContainer: { padding: 20, paddingBottom: 40 },
  currentPlanBox: {
    backgroundColor: 'rgba(20,30,60,0.85)',
    borderRadius: 16,
    padding: 20,
    marginBottom: 28,
    alignItems: 'flex-start',
  },
  currentPlanTitle: { color: '#ffd700', fontWeight: 'bold', fontSize: 16, marginBottom: 6 },
  currentPlanName: { color: '#fff', fontWeight: 'bold', fontSize: 22, marginBottom: 2 },
  currentPlanPrice: { color: '#b0b8ff', fontSize: 16, marginBottom: 8 },
  nextPaymentDate: { color: '#fff', fontSize: 14, marginBottom: 10 },
  currentPlanBtnRow: { flexDirection: 'row', gap: 10 },
  changePlanBtn: {
    backgroundColor: '#7b6cff',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 16,
    marginRight: 8,
  },
  changePlanBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 15 },
  cancelBtn: {
    backgroundColor: '#222b4c',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 16,
  },
  cancelBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 15 },
  plansRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 32 },
  planCard: {
    flex: 1,
    backgroundColor: 'rgba(20,30,60,0.85)',
    borderRadius: 16,
    marginHorizontal: 6,
    padding: 18,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  currentPlanCard: {
    backgroundColor: '#e6eaff',
    borderColor: '#7b6cff',
    shadowColor: '#7b6cff',
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  popularPlanCard: {
    borderColor: '#ffd700',
  },
  popularBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#ffd700',
    color: '#222',
    fontWeight: 'bold',
    fontSize: 12,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    zIndex: 2,
  },
  planName: { fontSize: 20, fontWeight: 'bold', color: '#fff', marginBottom: 4 },
  planLabel: { fontSize: 16, color: '#b0b8ff', marginBottom: 10 },
  planDescBox: { marginBottom: 16 },
  planDesc: { color: '#fff', fontSize: 13, marginBottom: 2 },
  planButton: {
    backgroundColor: '#222b4c',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 18,
    marginTop: 8,
  },
  currentPlanButton: {
    backgroundColor: '#7b6cff',
  },
  planButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 15 },
  currentPlanButtonText: { color: '#fff' },
  section: { backgroundColor: 'rgba(20,30,60,0.85)', borderRadius: 16, padding: 18 },
  sectionTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold', marginBottom: 16 },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  paymentDate: { color: '#b0b8ff', fontSize: 15 },
  paymentPlan: { color: '#fff', fontSize: 15 },
  paymentRight: { alignItems: 'flex-end' },
  paymentAmount: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  paymentStatusBox: {
    backgroundColor: '#1ed760',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 2,
    marginTop: 4,
  },
  paymentStatus: { color: '#fff', fontWeight: 'bold', fontSize: 13 },
  allHistoryBtn: { alignItems: 'center', marginTop: 10 },
  allHistoryText: { color: '#b0b8ff', fontSize: 15, textDecorationLine: 'underline' },
});

export default styles;
